name=htcw_frame
version=0.1.5
author=honey the codewitch
maintainer=honey the codewitch
sentence=Provides data transport framing and error checking
paragraph=This library provides data transport framing and error checking for dirty comms lines
category=Communication
url=https://github.com/codewitch-honey-crisis/htcw_frame
architectures=*
